name: "node Lint"
description: "Lints node based repository"
inputs:
  checkout-repo:
    required: false
    description: "Perform checkout as first step of action"
    default: "true"
  github-token:
    required: true
    description: "GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'"
  node-version:
    required: true
    description: "The version of Node.js to setup and use with Yarn"
    default: "16"
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install Yarn
      shell: bash
      run: npm install -g yarn
    - name: Install dependencies
      shell: bash
      run: yarn --pure-lockfile
    - name: Eslint
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ inputs.github-token }}
        eslint_flags: ./src --ext .ts
        reporter: github-check
    - name: Pre-commit
      uses: open-turo/action-pre-commit@v1
