name: node Lint
description: GitHub Action that lints a Node based repository
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    required: true
    description: GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'
  npm-auth-token:
    required: false
    description: The Node Package Manager (npm) authentication token
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - name: Setup tools
      uses: open-turo/action-setup-tools@v1
    - name: Install dependencies
      shell: bash
      run: yarn --pure-lockfile
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
    - name: Eslint
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ inputs.github-token }}
        eslint_flags: ./src --ext .ts
        reporter: github-check
    - name: Pre-commit
      uses: open-turo/action-pre-commit@v1
