name: node Lint
description: GitHub Action that lints a Node based repository
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  eslint-flags:
    required: false
    description: Flags and args of eslint command
  github-token:
    required: true
    description: GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'
    default: ${{ github.token }}
  npm-auth-token:
    required: false
    description: The Node Package Manager (npm) authentication token. This token is used to authenticate against a private NPM registry configured via a .npmrc file.
  npm-token:
    required: false
    description: The Node Package Manager (npm) authentication token. This token is used to authenticate against the NPM registry.
  internal-dependency-prefixes:
    required: false
    description: Prefixes used to match internal dependencies and disallow beta versions. Can take comma-separated values e.g. '@turo,@example'.
    default: ""
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - name: Setup tools
      uses: open-turo/action-setup-tools@v1
    - name: Check for yarn.lock
      id: check_yarn_lock
      uses: andstor/file-existence-action@v2
      with:
        files: yarn.lock
    - name: Install dependencies (yarn)
      if: steps.check_yarn_lock.outputs.files_exists == 'true'
      shell: bash
      run: yarn --pure-lockfile
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
    - name: Install dependencies (npm)
      if: steps.check_yarn_lock.outputs.files_exists == 'false'
      shell: bash
      run: npm ci
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
    - name: Run eslint
      shell: bash
      run: npx eslint ${{ inputs.eslint-flags }}
    - name: Pre-commit
      uses: open-turo/action-pre-commit@v1
    - if: ${{ inputs.internal-dependency-prefixes != '' }}
      name: Create Beta Release Check Script
      run: |
        cat << 'EOF' > "${{ runner.temp }}/beta-check.sh"
        set -e
        delimited_prefixes=$(sed 's/ *, */|/g' <<< $1)
        if egrep "($delimited_prefixes).*\-beta\-" package.json; then
          echo "ERROR: should not consume a beta version of an internal dependency. Make sure to revert/update to use a proper release."
          exit 1
        fi
        EOF
        chmod +x ${{ runner.temp }}/beta-check.sh
      shell: bash
    - if: ${{ inputs.internal-dependency-prefixes != '' }}
      name: Run Beta Release Check
      run: bash ${{ runner.temp }}/beta-check.sh ${{ inputs.internal-dependency-prefixes }}
      shell: bash
