name: GitHub Action Release & Publish
description: GitHub Action that publishes a new release.
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    required: true
    description: GitHub token that can checkout the repository as well as create tags/releases against it. e.g. 'secrets.GITHUB_TOKEN'
    default: ${{ github.token }}
  docker-config-file:
    required: false
    description: Path to the docker config file (defaults to .docker-config.json) Must contain imageName, may contain dockerfile.
    default: .docker-config.json
  docker-flavor:
    required: false
    description: Docker flavor to use for docker metadata
    default: |
      latest=false
  dockerhub-user:
    required: false
    description: username for dockerhub
  dockerhub-password:
    required: false
    description: password for dockerhub
  npm-auth-token:
    required: false
    description: The Node Package Manager (npm) authentication token. This token is used to authenticate against a private NPM registry configured via a .npmrc file.
  npm-token:
    required: false
    description: The Node Package Manager (npm) authentication token. This token is used to authenticate against the NPM registry.
  dry-run:
    required: false
    description: Whether to run semantic release in `dry-run` mode. It will override the `dryRun` attribute in your configuration file
    default: "false"
  extra-plugins:
    required: false
    description: Extra plugins for pre-install. You can also specify specifying version range for the extra plugins if you prefer.  Defaults to install @open-turo/semantic-release-config.
    default: |
      @open-turo/semantic-release-config
outputs:
  new-release-published:
    description: Whether a new release was published
    value: ${{ steps.release.outputs.new-release-published }}
  new-release-version:
    description: Version of the new release
    value: ${{ steps.release.outputs.new-release-version }}
  new-release-major-version:
    description: Major version of the new release
    value: ${{ steps.release.outputs.new-release-major-version }}
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: inputs.checkout-repo == 'true'
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup tools
      uses: open-turo/action-setup-tools@v1
    - name: Check for yarn.lock
      id: check_yarn_lock
      uses: andstor/file-existence-action@v2
      with:
        files: yarn.lock
    - name: Install dependencies (yarn)
      if: steps.check_yarn_lock.outputs.files_exists == 'true'
      shell: bash
      run: yarn --pure-lockfile
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
    - name: Install dependencies (npm)
      if: steps.check_yarn_lock.outputs.files_exists == 'false'
      shell: bash
      run: npm ci
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
    - name: Build
      uses: open-turo/actions-node/build@v5
      with:
        checkout-repo: false
    - name: Release
      id: release
      uses: open-turo/actions-release/semantic-release@v4
      with:
        dry-run: ${{ inputs.dry-run }}
        extra-plugins: ${{ inputs.extra-plugins }}
        github-token: ${{ inputs.github-token }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
    - uses: open-turo/actions-node/build-docker@v5
      id: docker-build
      if: inputs.dockerhub-user != '' && inputs.dockerhub-password != ''
      with:
        docker-config-file: ${{ inputs.docker-config-file }}
        dockerhub-user: ${{ inputs.dockerhub-user }}
        dockerhub-password: ${{ inputs.dockerhub-password }}
        github-token: ${{ inputs.github-token }}
        npm-auth-token: ${{ inputs.npm-auth-token }}
        npm-token: ${{ inputs.npm-token }}
        image-version: ${{ steps.release.outputs.new-release-version }}
        docker-flavor: ${{ inputs.docker-flavor }}
        docker-metadata-tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}},value=${{ steps.release.outputs.new-release-version }}
