name: GitHub Action Release & Publish
description: GitHub Action that publishes a new release.
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    required: true
    description: GitHub token that can checkout the repository as well as create tags/releases against it. e.g. 'secrets.GITHUB_TOKEN'
  npm-auth-token:
    required: true
    description: The Node Package Manager (npm) authentication token
  dry-run:
    required: false
    description: Whether to run semantic release in `dry-run` mode. It will override the `dryRun` attribute in your configuration file
    default: "false"
  extra-plugins:
    required: false
    description: Extra plugins for pre-install. You can also specify specifying version range for the extra plugins if you prefer.
outputs:
  new-release-published:
    description: Whether a new release was published
    value: ${{ steps.release.outputs.new-release-published }}
  new-release-version:
    description: Version of the new release
    value: ${{ steps.release.outputs.new-release-version }}
  new-release-major-version:
    description: Major version of the new release
    value: ${{ steps.release.outputs.release-major }}
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - name: Setup tools
      uses: open-turo/action-setup-tools@v1
    - name: Install dependencies
      shell: bash
      run: yarn --pure-lockfile
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
    - name: Build
      shell: bash
      run: yarn build
      env:
        NODE_ENV: production
        NPM_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
    - name: Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        dry_run: ${{ inputs.dry-run }}
        extra_plugins: ${{ inputs.extra-plugins }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
