name: Build & push docker images
description: Builds and push docker images for the input platform, tags and image version
inputs:
  docker-config-file:
    required: false
    description: Path to the docker config file (defaults to .docker-config.json) Must contain imageName, may contain dockerfile.
    default: .docker-config.json
  docker-flavor:
    required: false
    description: Docker flavor to use for docker metadata
    default: |
      latest=false
  docker-push:
    required: false
    description: Whether to push the image to the registry. Defaults to true.
    default: "true"
  docker-cache:
    required: false
    description: Whether to use Docker layer caching. Defaults to true.
    default: "true"
  dockerhub-user:
    required: true
    description: username for dockerhub
  dockerhub-password:
    required: true
    description: password for dockerhub
  github-token:
    required: true
    description: Usually secrets.GITHUB_TOKEN
  npm-auth-token:
    required: false
    description: The Node Package Manager (npm) authentication token. This token is used to authenticate against a private NPM registry configured via a .npmrc file. Gets pass to the docker build as a secret
  npm-token:
    required: false
    description: The Node Package Manager (npm) authentication token. This token is used to authenticate against the NPM registry. Gets passed to the docker build as a secret
  image-version:
    required: true
    description: Docker image version
  image-platform:
    description: Target platform to build image for (eg. linux/amd64 (default), linux/arm64, etc)
    required: false
    default: linux/amd64
  docker-metadata-tags:
    description: "'List of tags as key-value pair attributes' See: https://github.com/docker/metadata-action#tags-input"
    required: false
outputs:
  image-name:
    description: Docker image name
    value: ${{ steps.config.outputs.image-name }}
  image-with-tag:
    description: Full image with tag - <image-name>:<image-version>
    value: ${{ steps.config.outputs.image-name }}:${{ inputs.image-version }}
  image-digest:
    description: The digest for the docker image
    value: ${{ steps.docker-build-cached.outputs.digest || steps.docker-build-no-cache.outputs.digest }}
  cache-key:
    description: The cache key used for Docker layer caching (architecture-specific)
    value: buildcache-${{ steps.config.outputs.cache-suffix }}

runs:
  using: composite
  steps:
    - name: Dump GitHub context
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - id: config
      shell: bash
      env:
        DOCKER_CONFIG_FILE: ${{ inputs.docker-config-file }}
        IMAGE_VERSION: ${{ inputs.image-version }}
        IMAGE_PLATFORM: ${{ inputs.image-platform }}
        DOCKER_METADATA_TAGS: ${{ inputs.docker-metadata-tags }}
      run: |
        # if docker-config file does not exist - fail
        if [ ! -f "$DOCKER_CONFIG_FILE" ]; then
          echo "::error::Docker config file not found: $DOCKER_CONFIG_FILE" && exit 1
        fi
        image_name=$(jq -r .imageName $DOCKER_CONFIG_FILE)
        echo "image-name: ${image_name}"
        echo "image-name=${image_name}" >> $GITHUB_OUTPUT
        dockerfile=$(jq -r '.dockerfile // "./Dockerfile"' $DOCKER_CONFIG_FILE)
        echo "Dockerfile: ${dockerfile}"
        echo "dockerfile=${dockerfile}" >> $GITHUB_OUTPUT
        echo "image-version: $IMAGE_VERSION"
        echo "image-platform: $IMAGE_PLATFORM"
        echo "docker-metadata-tags: $DOCKER_METADATA_TAGS"

        # Generate architecture-specific cache suffix from platform
        # Examples: linux/amd64 -> amd64, linux/arm64/v8 -> arm64-v8
        cache_suffix=$(echo "$IMAGE_PLATFORM" | sed 's|linux/||' | sed 's|/|-|g')
        echo "cache-suffix: ${cache_suffix}"
        echo "cache-suffix=${cache_suffix}" >> $GITHUB_OUTPUT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-user }}
        password: ${{ inputs.dockerhub-password }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ steps.config.outputs.image-name }}
        flavor: ${{ inputs.docker-flavor }}
        tags: |
          ${{ inputs.docker-metadata-tags }}
    - name: Build and push (with cache)
      if: inputs.docker-cache == 'true'
      uses: docker/build-push-action@v6
      id: docker-build-cached
      with:
        context: .
        platforms: ${{ inputs.image-platform }}
        file: ${{ steps.config.outputs.dockerfile }}
        build-args: |
          GIT_COMMIT=${{ github.sha }}
          BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          VERSION=${{ inputs.image-version }}
          REVISION=${{ inputs.image-version }}
          BRANCH=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.branch'] }}
        secrets: |
          NPM_AUTH_TOKEN=${{ inputs.npm-auth-token }}
          NPM_TOKEN=${{ inputs.npm-token }}
        push: ${{ inputs.docker-push == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: |
          type=registry,ref=docker.io/${{ steps.config.outputs.image-name }}:buildcache-${{ steps.config.outputs.cache-suffix }}
        cache-to: |
          type=registry,ref=docker.io/${{ steps.config.outputs.image-name }}:buildcache-${{ steps.config.outputs.cache-suffix }},mode=max,compression=zstd
    - name: Build and push (without cache)
      if: inputs.docker-cache != 'true'
      uses: docker/build-push-action@v6
      id: docker-build-no-cache
      with:
        context: .
        platforms: ${{ inputs.image-platform }}
        file: ${{ steps.config.outputs.dockerfile }}
        build-args: |
          GIT_COMMIT=${{ github.sha }}
          BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          VERSION=${{ inputs.image-version }}
          REVISION=${{ inputs.image-version }}
          BRANCH=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.branch'] }}
        secrets: |
          NPM_AUTH_TOKEN=${{ inputs.npm-auth-token }}
          NPM_TOKEN=${{ inputs.npm-token }}
        push: ${{ inputs.docker-push == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
