name: CI

on:
  push:

jobs:
  release-notes:
    name: Release notes preview
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: open-turo/actions-release/release-notes-preview@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/lint@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/test@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
